language: ruby
sudo: false

rvm:
  - 2.3.4

script:
  - RAIL_ENV=production rake assets

deploy:
  github_token: $GITHUB_TOKEN
  local_dir: public
  provider: pages
  skip_cleanup: true

env:
  global:
    secure: HG+x6YgUgerbGwF0bT1XPYqeFUWJagQCDtATwKT3MUtbb+zaz1IWKzezxztPRzz5J02BteJv5V9gyun6qykdWssCn4iYO1kEBo/8lAvg8t2VXCIeosYwa1Au4bchiWroyFl2zD/nQIsSBdWFOdH2QZG/aZCUKj9bILh23ZenqTI=

notifications:
  email: false
