name: Deployment

on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Configure Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.3.4
          bundler-cache: true

      - name: Build the site
        run: |
          RAIL_ENV=production bundle exec rake assets

      - name: Deploy the site
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: public
